# Isaac Sim Dataset Configuration for PoET
# Configuration file for training PoET on Isaac Sim dataset

# Dataset paths
dataset_path: '/data/gplong/force_map_project/w-poet/poet/dataset_files/isaac_sim_annotations'
synt_background: null  # No synthetic background needed for Isaac Sim data

# MaskRCNN backbone configuration
anchor_sizes:
-
  - 32
-
  - 64
-
  - 128
-
  - 256
-
  - 512
backbone_str: resnet50-fpn
input_resize:
- 480
- 640
label_to_category_id:
  background: 0
  obj_000001: 1
  obj_000002: 2
  obj_000003: 3
  obj_000004: 4
  obj_000005: 5
  obj_000006: 6
  obj_000007: 7
  obj_000008: 8
  obj_000009: 9
  obj_000010: 10
  obj_000011: 11
  obj_000012: 12
  obj_000013: 13
  obj_000014: 14
  obj_000015: 15
  obj_000016: 16
  obj_000017: 17
  obj_000018: 18
  obj_000019: 19
  obj_000020: 20
  obj_000021: 21

# Model configuration
num_classes: 22  # 21 object classes + 1 background
num_queries: 20
aux_loss: true

# Graph Transformer and Force Prediction
use_graph_transformer: true
use_force_prediction: true
graph_hidden_dim: 256  # Same as hidden_dim
graph_num_layers: 4
graph_num_heads: 4

# Training parameters
lr: 1e-4
lr_backbone: 1e-5
batch_size: 2
weight_decay: 1e-4
epochs: 300
lr_drop: 200
clip_max_norm: 0.1

# Data augmentation
rgb_augmentation: true
grayscale: false

# Bounding box settings
bbox_mode: 'gt'  # Use ground truth bounding boxes
jitter_probability: 0.5

# Model architecture
backbone: 'resnet50'
position_embedding: 'sine'
hidden_dim: 256
nheads: 8
enc_layers: 6
dec_layers: 6
dim_feedforward: 1024
dropout: 0.1

# Loss weights
mask_loss_coef: 1
dice_loss_coef: 1
bbox_loss_coef: 5
giou_loss_coef: 2
eos_coef: 0.1
pose_loss_coef: 1
translation_loss_coef: 1
rotation_loss_coef: 1
force_loss_coef: 1.0

# Evaluation
eval_every: 10
save_every: 50

# Device settings
device: 'cuda'
num_workers: 4
cache_mode: false

# Output directory
output_dir: './results/isaac_sim_training'

# Resume training (optional)
# resume: './path/to/checkpoint.pth'

# Pretrained model (optional)
# pretrained: './path/to/pretrained_model.pth'

# Class names file
classes_file: '/data/gplong/force_map_project/w-poet/poet/dataset_files/isaac_sim_annotations/classes.json'

# Symmetries file
symmetries_file: '/data/gplong/force_map_project/w-poet/poet/dataset_files/isaac_sim_symmetries.json'